# Generated by Django 4.1.5 on 2024-09-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_equipment_delete_asset_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='acquire_date',
            new_name='purchased_date',
        ),
    ]
