# Generated by Django 4.1.5 on 2024-09-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_acquire_date_equipment_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('technician', 'Technician'), ('administrator', 'Administrator'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchased_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
