# Generated by Django 4.1.5 on 2024-09-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employee_position_errorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=10),
        ),
    ]
